int l1 = 3;
int l2 = 4;
int l3 = 5;
int l4 = 6;
int l5 = 7;
int l6 = 8;
int l7 = 9;
int l8 = 11;
int l9 = 12;
int l10 = 13;
int ms = 2;
void setup() {
  Serial.begin(9600);
  pinMode(ms,INPUT);
  pinMode(l1,OUTPUT);
  pinMode(l2,OUTPUT);
  pinMode(l3,OUTPUT);
  pinMode(l4,OUTPUT);
  pinMode(l5,OUTPUT);
  pinMode(l6,OUTPUT);
  pinMode(l7,OUTPUT);
  pinMode(l8,OUTPUT);
  pinMode(l9,OUTPUT);
  pinMode(l10,OUTPUT);
}
void loop() {
  int bs = analogRead(ms);
  Serial.println(bs);
  if(bs>=225){
    digitalWrite(l1,LOW);
    digitalWrite(l2,LOW);
    digitalWrite(l3,LOW);
    digitalWrite(l4,LOW);
    digitalWrite(l5,LOW);
    digitalWrite(l6,LOW);
    digitalWrite(l7,LOW);
    digitalWrite(l8,LOW);
    digitalWrite(l9,LOW);
    digitalWrite(l10,LOW);
    digitalWrite(l1,HIGH);
  } else if(bs>=200){
    digitalWrite(l1,LOW);
    digitalWrite(l2,LOW);
    digitalWrite(l3,LOW);
    digitalWrite(l4,LOW);
    digitalWrite(l5,LOW);
    digitalWrite(l6,LOW);
    digitalWrite(l7,LOW);
    digitalWrite(l8,LOW);
    digitalWrite(l9,LOW);
    digitalWrite(l10,LOW);
    digitalWrite(l1,HIGH);
    digitalWrite(l2,HIGH);
  } else if(bs>=175){
    digitalWrite(l1,LOW);
    digitalWrite(l2,LOW);
    digitalWrite(l3,LOW);
    digitalWrite(l4,LOW);
    digitalWrite(l5,LOW);
    digitalWrite(l6,LOW);
    digitalWrite(l7,LOW);
    digitalWrite(l8,LOW);
    digitalWrite(l9,LOW);
    digitalWrite(l10,LOW);
    digitalWrite(l1,HIGH);
    digitalWrite(l2,HIGH);
    digitalWrite(l3,HIGH); 
    } else if(bs>=150){
    digitalWrite(l1,LOW);
    digitalWrite(l2,LOW);
    digitalWrite(l3,LOW);
    digitalWrite(l4,LOW);
    digitalWrite(l5,LOW);
    digitalWrite(l6,LOW);
    digitalWrite(l7,LOW);
    digitalWrite(l8,LOW);
    digitalWrite(l9,LOW);
    digitalWrite(l10,LOW);
    digitalWrite(l1,HIGH);
    digitalWrite(l2,HIGH);
    digitalWrite(l3,HIGH);
    digitalWrite(l4,HIGH);
    } else if(bs>=125){
    digitalWrite(l1,LOW);
    digitalWrite(l2,LOW);
    digitalWrite(l3,LOW);
    digitalWrite(l4,LOW);
    digitalWrite(l5,LOW);
    digitalWrite(l6,LOW);
    digitalWrite(l7,LOW);
    digitalWrite(l8,LOW);
    digitalWrite(l9,LOW);
    digitalWrite(l10,LOW);
    digitalWrite(l1,HIGH);
    digitalWrite(l2,HIGH);
    digitalWrite(l3,HIGH);
    digitalWrite(l4,HIGH);
    digitalWrite(l5,HIGH);
    } else if(bs>=100){
    digitalWrite(l1,LOW);
    digitalWrite(l2,LOW);
    digitalWrite(l3,LOW);
    digitalWrite(l4,LOW);
    digitalWrite(l5,LOW);
    digitalWrite(l6,LOW);
    digitalWrite(l7,LOW);
    digitalWrite(l8,LOW);
    digitalWrite(l9,LOW);
    digitalWrite(l10,LOW);
    digitalWrite(l1,HIGH);
    digitalWrite(l2,HIGH);
    digitalWrite(l3,HIGH);
    digitalWrite(l4,HIGH);
    digitalWrite(l5,HIGH);
    digitalWrite(l6,HIGH);
    } else if(bs>=75){
    digitalWrite(l1,LOW);
    digitalWrite(l2,LOW);
    digitalWrite(l3,LOW);
    digitalWrite(l4,LOW);
    digitalWrite(l5,LOW);
    digitalWrite(l6,LOW);
    digitalWrite(l7,LOW);
    digitalWrite(l8,LOW);
    digitalWrite(l9,LOW);
    digitalWrite(l10,LOW);
    digitalWrite(l1,HIGH);
    digitalWrite(l2,HIGH);
    digitalWrite(l3,HIGH);
    digitalWrite(l4,HIGH);
    digitalWrite(l5,HIGH);
    digitalWrite(l6,HIGH);
    digitalWrite(l7,HIGH);
    } else if(bs>=50){
    digitalWrite(l1,LOW);
    digitalWrite(l2,LOW);
    digitalWrite(l3,LOW);
    digitalWrite(l4,LOW);
    digitalWrite(l5,LOW);
    digitalWrite(l6,LOW);
    digitalWrite(l7,LOW);
    digitalWrite(l8,LOW);
    digitalWrite(l9,LOW);
    digitalWrite(l10,LOW);
    digitalWrite(l1,HIGH);
    digitalWrite(l2,HIGH);
    digitalWrite(l3,HIGH);
    digitalWrite(l4,HIGH);
    digitalWrite(l5,HIGH);
    digitalWrite(l6,HIGH);
    digitalWrite(l7,HIGH);
    digitalWrite(l8,HIGH);
    } else if(bs>=25){
    digitalWrite(l1,LOW);
    digitalWrite(l2,LOW);
    digitalWrite(l3,LOW);
    digitalWrite(l4,LOW);
    digitalWrite(l5,LOW);
    digitalWrite(l6,LOW);
    digitalWrite(l7,LOW);
    digitalWrite(l8,LOW);
    digitalWrite(l9,LOW);
    digitalWrite(l10,LOW);
    digitalWrite(l1,HIGH);
    digitalWrite(l2,HIGH);
    digitalWrite(l3,HIGH);
    digitalWrite(l4,HIGH);
    digitalWrite(l5,HIGH);
    digitalWrite(l6,HIGH);
    digitalWrite(l7,HIGH);
    digitalWrite(l8,HIGH);
    digitalWrite(l9,HIGH);    
    } else if(bs>=0){
    digitalWrite(l1,LOW);
    digitalWrite(l2,LOW);
    digitalWrite(l3,LOW);
    digitalWrite(l4,LOW);
    digitalWrite(l5,LOW);
    digitalWrite(l6,LOW);
    digitalWrite(l7,LOW);
    digitalWrite(l8,LOW);
    digitalWrite(l9,LOW);
    digitalWrite(l10,LOW);
    digitalWrite(l1,HIGH);
    digitalWrite(l2,HIGH);
    digitalWrite(l3,HIGH);
    digitalWrite(l4,HIGH);
    digitalWrite(l5,HIGH);
    digitalWrite(l6,HIGH);
    digitalWrite(l7,HIGH);
    digitalWrite(l8,HIGH);
    digitalWrite(l9,HIGH);                               
    digitalWrite(l10,HIGH);
    }
delay(1);
}
